blueprint:
  name: Washer Dryer Ready
  description: Tells when washer dryer done
  domain: automation
  sensors:
      washing_maching_is_running:
        friendly_name: Washing Machine Is Running
        value_template: >-
          {% if states('sensor.laundry_11_1min')|float < 5 %}
               notify.mobile_app_iphonedee
          {% else %}
            false
          {% endif %} 
