blueprint:
  name: Washer Dryer Ready
  description: Tells when washer dryer done
  domain: automation
  sensors:
      washing_maching_is_running:
        friendly_name: Washing Machine Is Running
        value_template: >-
          {% if states('sensor.washing_machine_power_switch_power')|float > 3 %}
            true
          {% else %}
            false
          {% endif %} 
